startup_verify = true
startup_update = true
download_all_versions = true

[mirror]
index = "https://github.com/rust-lang/crates.io-index/"

[config]
dl = "http://localhost:8080/api/v1/crates"
api = "http://localhost:8080/"

[overlays]
my_index = "my_custom_index/"
